### ISSUE TITLE
Unable to Load Mitsuba (Windows 10)

### ISSUE THREAD

**Issue by RuijiaX** [CMURoboTouch/mitsuba2-python-package#2]
Hi! I ran into some problem when I was trying to activate mitsuba but I am not sure what I should do.

After cloning the `mitsuba2-python-package` repository successfully, I tried to activate mitsuba, but it tells me that mitsuba is not activated when I tested it by calling the `test_mitsuba.py`. Below is a screenshot of the messages I got.

![image](https://user-images.githubusercontent.com/44103895/106366847-9118a180-630c-11eb-8571-d1390723bfd0.png)

Thank you!

**Comment by arpit15** [comment]
For windows, you have to use following steps
1. Install anaconda. Follow instructions mentioned [here](https://docs.anaconda.com/anaconda/install/windows/)
2. Open Anaconda Navigator 
3. Open Anaconda Terminal. 
![anaconda_terminal](https://user-images.githubusercontent.com/4703676/106371316-09915980-6331-11eb-9e3a-6568358f72a1.png)
4. Navigate to the `mitsuba2-python-package` directory
5. Use the following command `setpath_win.bat`
6. Test if mitsuba2 is setup properly by running `python3 test_mitsuba.py`

**Comment by arpit15** [comment]
After running `setpath_win.bat`, please post the output of following command in anaconda terminal
```
echo %PATH%
echo %PYTHONPATH%
```

**Comment by RuijiaX** [comment]
This the the output I got after adding the above command:

![image](https://user-images.githubusercontent.com/44103895/106392721-18275180-63c1-11eb-9446-b1ece13d9db3.png)

**Comment by arpit15** [comment]
You don't need to add the following lines to .bat file. You can just type those commands in terminal. The output seems good enough.
Can you post following details?
1. Anaconda version
2. Windows version. Follow steps mentioned [here](https://support.microsoft.com/en-us/windows/see-which-version-of-windows-10-you-have-12d35019-4da9-0cb1-ba47-f8b031b712ad)
3. Python version. Can use `python3 --version`

**Comment by RuijiaX** [comment]
1. Anaconda version is 4.9.2
2. Windows version is 2004
3. Python version is 3.8.5

Thank you for helping me!

**Comment by arpit15** [comment]
I am unable to update my windows version. We can try to debug it in our meeting.

**Comment by RuijiaX** [comment]
Okk! Thank you!

**Comment by arpit15** [comment]
The issue turned out to be an incomplete repository download.
