### ISSUE TITLE
Unable to load mitsuba

### ISSUE THREAD

**Issue by Nnboy** [CMURoboTouch/mitsuba2-python-package#4]
## Summary

*Unable to load mitsuba*

## System configuration

- Platform: Ubuntu 18.04
- Python version: 3.7.7

## Description

```shell
(mitsuba) nnboy@lhj:~/opensource/mitsuba2-python-package-main$ source setpath_linux.sh
(mitsuba) nnboy@lhj:~/opensource/mitsuba2-python-package-main$ python test_mitsuba.py
Unable to load mitsuba
The 'mitsuba' native modules could not be imported. You're likely trying to use Mitsuba within a Python binary (/home/nnboy/anaconda3/envs/mitsuba/bin/python3) that is different from the one for which the native module was compiled (/home/arpit/.pyenv/versions/py377/bin/python).
```

**Comment by arpit15** [comment]
We support Ubuntu 20.04 only. For other platforms, you can follow the [instructions](https://mitsuba2.readthedocs.io/en/latest/src/getting_started/compiling.html) at the official webpage with the modified branch available [here](https://github.com/arpit15/mitsuba2/tree/shapeupdate)
